# Generated by Django 5.2.18 on 2026-10-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField()),
                ('memory_total_bytes', models.BigIntegerField()),
                ('memory_used_bytes', models.BigIntegerField()),
                ('memory_percent', models.FloatField()),
                ('disk_total_bytes', models.BigIntegerField()),
                ('disk_used_bytes', models.BigIntegerField()),
                ('disk_percent', models.FloatField()),
                ('uptime_seconds', models.BigIntegerField()),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='infrastructure.server')),
            ],
            options={
                'verbose_name': 'server telemetry',
                'verbose_name_plural': 'server telemetry',
            },
        ),
    ]
