# Generated by Django 5.2.18 on 2026-10-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_server_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerHostState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('permission_denied', 'Permission denied'), ('error', 'Error')], max_length=32)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docker_host', to='infrastructure.server')),
            ],
            options={
                'verbose_name': 'Docker host state',
                'verbose_name_plural': 'Docker host states',
            },
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('running', 'Running'), ('exited', 'Exited'), ('paused', 'Paused'), ('restarting', 'Restarting'), ('created', 'Created'), ('dead', 'Dead'), ('unknown', 'Unknown')], max_length=32)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('starting', 'Starting'), ('none', 'None'), ('unknown', 'Unknown')], max_length=32)),
                ('container_created_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('present', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_containers', to='infrastructure.server')),
            ],
            options={
                'verbose_name': 'Docker container',
                'verbose_name_plural': 'Docker containers',
                'ordering': ['name', 'container_id'],
                'indexes': [models.Index(fields=['server', 'present'], name='infrastruct_server__f902dd_idx'), models.Index(fields=['state'], name='infrastruct_state_140a5c_idx')],
                'constraints': [models.UniqueConstraint(fields=('server', 'container_id'), name='uniq_server_docker_container_id')],
            },
        ),
    ]
