# Generated by Django 5.2.18 on 2026-10-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_docker_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerhoststate',
            name='last_discovered_at',
            field=models.DateTimeField(blank=True, help_text='When the last successful (authoritative) discovery was received.', null=True),
        ),
        # Drop only the redundant index; AlterField would also drop and
        # re-validate the foreign key constraint.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    # Covered by the (server_id, container_id) unique index.
                    sql='DROP INDEX IF EXISTS "infrastructure_dockercontainer_server_id_554d77f1"',
                    reverse_sql='CREATE INDEX IF NOT EXISTS "infrastructure_dockercontainer_server_id_554d77f1" ON "infrastructure_dockercontainer" ("server_id")',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='dockercontainer',
                    name='server',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='docker_containers', to='infrastructure.server'),
                ),
            ],
        ),
    ]
