# Generated by Django 5.2.18 on 2026-10-08 20:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hostname_or_ip', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('icmp', 'ICMP'), ('tcp', 'TCP')], max_length=8)),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('enabled', models.BooleanField(default=True)),
                ('monitoring_interval_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(86400)])),
                ('timeout_seconds', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('expected_sla_percentage', models.DecimalField(decimal_places=2, default=99.9, help_text='Informational SLA expectation for future reporting (not calculated yet).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('circuit_identifier', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_targets', to='agents.agent')),
            ],
            options={
                'verbose_name': 'network target',
                'verbose_name_plural': 'network targets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkMeasurement',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('packet_loss_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('probe_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('successful_probes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('failure_reason', models.CharField(blank=True, choices=[('', 'None'), ('timeout', 'Timeout'), ('connection_refused', 'Connection refused'), ('host_unreachable', 'Host unreachable'), ('dns_failure', 'DNS failure'), ('permission_denied', 'Permission denied'), ('unsupported', 'Unsupported'), ('network_error', 'Network error'), ('unknown', 'Unknown')], default='', max_length=32)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_measurements', to='agents.agent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='network.networktarget')),
            ],
            options={
                'verbose_name': 'network measurement',
                'verbose_name_plural': 'network measurements',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='networktarget',
            index=models.Index(fields=['assigned_agent', 'enabled'], name='network_net_assigne_2a41c7_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmeasurement',
            index=models.Index(fields=['target', '-measured_at'], name='network_net_target__ece8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmeasurement',
            index=models.Index(fields=['agent', '-measured_at'], name='network_net_agent_i_586b55_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmeasurement',
            index=models.Index(fields=['measured_at'], name='network_net_measure_2c6b8d_idx'),
        ),
    ]
