# Generated by Django 5.2.18 on 2026-10-08 20:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktarget',
            name='expected_sla_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.90'), help_text='Informational SLA expectation for future reporting (not calculated yet).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
