# Generated by Django 5.2.18 on 2026-10-09 09:28
#
# Deleting an agent no longer cascades to network targets and historical
# measurements (on_delete is enforced by Django, not by the database).
#
# The database side is written by hand: Django's AlterField would drop and
# re-add each foreign key, re-validating every measurement row under a lock.
# Only the cheap statements are needed: allow NULL and drop the single-column
# FK indexes that duplicate the leading column of existing composite indexes.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial_agent'),
        ('network', '0002_sla_default_decimal'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "network_networkmeasurement" ALTER COLUMN "agent_id" DROP NOT NULL',
                        'ALTER TABLE "network_networktarget" ALTER COLUMN "assigned_agent_id" DROP NOT NULL',
                        # Covered by (agent_id, measured_at DESC).
                        'DROP INDEX IF EXISTS "network_networkmeasurement_agent_id_f7c17dfb"',
                        # Covered by (target_id, measured_at DESC).
                        'DROP INDEX IF EXISTS "network_networkmeasurement_target_id_c2a21395"',
                        # Covered by (assigned_agent_id, enabled).
                        'DROP INDEX IF EXISTS "network_networktarget_assigned_agent_id_490a37b1"',
                    ],
                    reverse_sql=[
                        'CREATE INDEX IF NOT EXISTS "network_networktarget_assigned_agent_id_490a37b1" ON "network_networktarget" ("assigned_agent_id")',
                        'CREATE INDEX IF NOT EXISTS "network_networkmeasurement_target_id_c2a21395" ON "network_networkmeasurement" ("target_id")',
                        'CREATE INDEX IF NOT EXISTS "network_networkmeasurement_agent_id_f7c17dfb" ON "network_networkmeasurement" ("agent_id")',
                        # Fails if rows were detached from a deleted agent meanwhile.
                        'ALTER TABLE "network_networktarget" ALTER COLUMN "assigned_agent_id" SET NOT NULL',
                        'ALTER TABLE "network_networkmeasurement" ALTER COLUMN "agent_id" SET NOT NULL',
                    ],
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='networkmeasurement',
                    name='agent',
                    field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_measurements', to='agents.agent'),
                ),
                migrations.AlterField(
                    model_name='networkmeasurement',
                    name='target',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='network.networktarget'),
                ),
                migrations.AlterField(
                    model_name='networktarget',
                    name='assigned_agent',
                    field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_targets', to='agents.agent'),
                ),
            ],
        ),
    ]
